### ISSUE TITLE
SAT.py gives errors

### ISSUE THREAD

**Issue by aykutbulut** [coin-or/GiMPy#6]
I get the following errors when I run SAT.py.

Error: Layout type: "dot2tex" not recognized. Use one of: circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
Error: Layout was not done.  Missing layout plugins?

The problem is gone when I change the layout to "dot". Is this right or something else is intended?

**Comment by tkralphs** [comment]
There are two problems here. First, dot2tex only works with the display mode `'file'`, so I fixed that in the example and also added a check for that in `graph.py`. In addition, though, the `dot2tex` package itself seems to be broken (see https://github.com/kjellmf/dot2tex/issues/50), so I disabled that mode for now.

**Comment by tkralphs** [comment]
This seems to be working again now with the latest release of dot2tex.
