### ISSUE TITLE
The code seems written in python2 and xdot no longer support python2

### ISSUE THREAD

**Issue by gotakeoff** [coin-or/GiMPy#8]
Hi, I'm trying to learn from your code,but many of the examples seems can't work well(I really tried many ways to make it work). I would be very thankful if you can update the code in python3~

**Comment by tkralphs** [comment]
Just for historical documentation, everything should work well if one follows the installation instructions strictly (see the [README](https://github.com/coin-or/GiMPy/blob/master/README.md)). In particular, you need to force the installation of an older version of xdot.

**Comment by tkralphs** [comment]
I should also mention that xdot is not required. You can also display graphs just as PNG files or using [PyGame](http://www.pygame.org/).

**Comment by gotakeoff** [comment]
thanks for your reply. I used pygame to display those graphs and really learned from your code.
